auth:
    server:
        host: "localhost"
        port: 8002
        debug: True
    logger:
        name: "AUTH"
        level: "INFO"
        enable_console_logging: True
        enable_file_logging: True
        log_dir: "logs/service_logs"
