defaults:
    - app_config
    - auth_config
    - booking_config
    - service_config
    - technician_config
    - user_config
    - search_config
    - _self_

database:
    db_file: "hot_start.sqlite3"
    url: "sqlite:///./database/${database.db_file}"

app_logger:
    enable_logging: True
    log_dir: "logs"
    log_file: "main.log"

media:
    media_dir: "media"

hydra:
    output_subdir: "../logs/hydra_logs/"
