search:
    server:
        host: "0.0.0.0"
        port: 8005
        debug: True
    logger:
        name: "SEARCH"
        level: "INFO"
        enable_console_logging: True
        enable_file_logging: True
        log_dir: "logs/service_logs"
    db_file: "database/services.json"
