technician:
    server:
        host: "0.0.0.0"
        port: 8001
        debug: True
    logger:
        name: "TECHNICIAN"
        level: "INFO"
        enable_console_logging: True
        enable_file_logging: True
        log_dir: "logs/service_logs"
