user:
    server:
        host: "0.0.0.0"
        port: 8000
        debug: True
    logger:
        name: "USER"
        level: "INFO"
        enable_console_logging: True
        enable_file_logging: True
        log_dir: "logs/service_logs"
