
@port=8002
@hashed_password="95d30169a59c418b52013315fc81bc99fdf0a7b03a116f346ab628496f349ed5"

### User Registration [hashed_password = sha256_hash("secretpassword")]
POST http://127.0.0.1:{{port}}/register
Content-Type: application/json

{
  "email": "vijay@example.com",
  "phone": "1239867890",
  "name": "vijay",
  "hashed_password": "vijay"
}

###

### Technician Registration [hashed_password = sha256_hash("secretpassword")]
POST http://127.0.0.1:{{port}}/technician_register
Content-Type: application/json

{
  "email": "ss@example.com",
  "phone": "9876593210",
  "name": "Jane",
  "id_proof_type": "Aadhaar",
  "id_proof_number": "123456789101",
  "hashed_password": "1234",
  "service_category": "Electrical Services"
}

###

### User Login (Get JWT)
POST http://127.0.0.1:{{port}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "hashed_password": {{hashed_password}}
}

### (After successful login, copy the token from the response)
@user_jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJOb25lIiwidXNlcl90eXBlIjoidXNlciIsImV4cCI6MTc0MDc2NTg5OCwiaWF0IjoxNzM5OTAxODk4fQ.pJ1pJMd6z2wXdXSbyOFMh8ZKFGELYkWC_iBbEl23OC0


###

### Technician Login (Get JWT)
POST http://127.0.0.1:{{port}}/technician_login
Content-Type: application/json

{
  "email": "jane.doe@example.com", 
  "hashed_password": {{hashed_password}}
}

### (After successful login, copy the token from the response)
@technician_jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiJOb25lIiwidXNlcl90eXBlIjoidGVjaG5pY2lhbiIsImV4cCI6MTc0MDA3NTIwNSwiaWF0IjoxNzM5OTAyNDA1fQ.78NXI0tV_8f_rkh06ZO-WLLVZ7U8O_OaB-5H2AnpWl0

###

### Protected Route (User - requires JWT)
GET http://127.0.0.1:{{port}}/protected
Authorization: Bearer {{user_jwt}}


###

### Protected Route (Technician - requires JWT)
GET http://127.0.0.1:{{port}}/technician_protected
Authorization: Bearer {{technician_jwt}}