# Kindly check the server port for 'service' service before executing
@port=8003 

### Create a service
POST http://localhost:{{port}}/services
Content-Type: application/json

{
  "title": "Example Service",
  "service_category": "Plumbing Services", 
  "description": "This is an example service description.",
  "price": 50.00
}

### Get all services
GET http://localhost:{{port}}/services

### Get a specific service
GET http://localhost:{{port}}/services/1 

### Create a service with media files
### Present in the tests/service_test.py file

### Update a service
PUT http://localhost:{{port}}/services/1
Content-Type: application/json

{
  "title": "Updated Example Service",
  "description": "This is an updated description.",
  "service_category": "Carpentry Services" 
}

### Update a service with new media files
### Present in the tests/service_test.py file

### Get Media files of a service
GET http://localhost:{{port}}/services/media_file?path=media/Plumbing%20Services/Example%20Service%202/0e3daf83-57a2-4129-b07e-74433364f182_Plumbing-Carpentry-Services-20210528075631.2597370015.jpg


### Delete a service
DELETE http://localhost:{{port}}/services/1