# Kindly check the server port for 'user' service before executing

@port=8000

### Create a user [hashed_password = sha256_hash("secretpassword")]
POST http://localhost:{{port}}/users
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "phone": "1234567891",
  "name": "John Doe",
  "hashed_password": "95d30169a59c418b52013315fc81bc99fdf0a7b03a116f346ab628496f349ed5"
}

### Get user by UID
### This uid is received on the create user response
@uid=83075689-9319-419b-a60c-9f9235960189

GET http://localhost:8000/users/18dc5340-3af2-41de-9aaf-c681ccde45f9

### Get User by Email
GET http://localhost:{{port}}/users?email=john.doe@example.com

### Update User by UID
PUT http://localhost:{{port}}/users/{{uid}}
Content-Type: application/json

{
  "name": "Updated Test User" 
}

### Delete User by UID
DELETE http://localhost:{{port}}/users/{{uid}}