# Kindly check the server port for 'user' service before executing

@port=8000

### Create a user [hashed_password = sha256_hash("secretpassword")]
POST http://localhost:{{port}}/users
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "phone": "1234567891",
  "name": "John Doe",
  "hashed_password": "95d30169a59c418b52013315fc81bc99fdf0a7b03a116f346ab628496f349ed5"
}

### Get user by UID
GET http://localhost:{{port}}/users/1

### Get User by Email
GET http://localhost:{{port}}/users?email=john.doe@example.com

### Update User by UID
PUT http://localhost:{{port}}/users/1
Content-Type: application/json

{
  "name": "Updated Test User" 
}

### Delete User by UID
DELETE http://localhost:{{port}}/users/1